import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import { useState } from "react";
import { ChatTest } from "../src/components/features/chat/test";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const [roomId, setRoomId] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className="text-center font-bold  text-4xl	">Why Splint It?</p>
        <p className="text-center font-bold  text-5xl	mt-2 mb-4 tracking-wide">
          because <span className="text-indigo-600">Splint</span> means to{" "}
          {"  "}
          <span className="text-indigo-600">Support.</span>
        </p>
        <h2 className="text-xl text-gray-500 m-0 font-medium tracking-wide">
          Hassle Free Support management, add a splint to all cracks!
        </h2>
        <Link
          href={"/demo"}
          className="flex item-center justify-center mt-8 -ml-16"
        >
          <button className="hover:scale-105 transition-all duration-300 tracking-wide text-3xl bg-indigo-500 py-3 px-8 rounded-full mt-4 tracking-wide text-gray-100 form-indigo-500 to-sky-600">
            Demo
          </button>
        </Link>
      </main>
    </div>
  );
};

export default Home;
